#!/bin/sh

# source xinitrc.d files
# if [ -d /etc/X11/xinit/xinitrc.d ] ; then
#  for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
#   [ -x "$f" ] && . "$f"
#  done
#  unset f
# fi

# launch ssh agent
# eval $(ssh-agent)

# exec herbstluftwm --locked
exec dwm
# exec firefox
# exec dwm
# exec awesome
